# Generated by Django 2.2.9 on 2020-01-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 's', 'verbose_name_plural': 'ss'},
        ),
    ]
