# Generated by Django 3.0.2 on 2020-01-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(max_length=50, verbose_name='Название тэга')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_Title', models.CharField(max_length=50, verbose_name='Заголовок статьи')),
                ('Note_Text', models.TextField(verbose_name='Текст статьи')),
                ('Note_Pub_Date', models.DateField()),
                ('Note_Author', models.CharField(max_length=15, verbose_name='Автор статьи')),
                ('Note_FK_Tag', models.ManyToManyField(to='News.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_Author', models.CharField(max_length=50, verbose_name='Автор комментария')),
                ('Comment_Text', models.TextField(max_length=144, verbose_name='Текст комментария')),
                ('Comment_Pub_DateTime', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('Comment_FK_Note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Notes')),
            ],
        ),
    ]
